import React from "react";
import Head from 'next/head'

type headProps = {
    title: string;
}
const Heads:React.FC<headProps> = ( { title }) => {
    return(
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <link rel="shortcut icon" href="/favicon/favicon.ico" />
                <title>{ title }</title>
            </Head>
        </>
    )
}

export default Heads;